#!/bin/env bash

# Verificar si se proporciona una dirección IP como argumento
if [ $# -eq 0 ]; then
    echo "Uso: $0 {DIRECCIÓN_IP}"
        exit 1
	fi

# Realizar un ping a la dirección IP proporcionada 5 veces
	ping -c 5 $1

